const products = [
  {
    cod: "1",
    name: "Queijo Mussarela",
    price: 51.0,
    unit: "kg",
    marca: "Davac",
    category: "Frios",
    description: "",
    image: "",
  },
  {
    cod: "2",
    name: "Presunto",
    price: 26.0,
    unit: "kg",
    marca: "Seaara",
    category: "Frios",
    description: "",
    image: "",
  },
  {
    cod: "3",
    name: "H2o Limoneto",
    price: 6.99,
    unit: "un",
    size: "1.5L",
    marca: "",
    category: "Bebidas",
    description: "",
    image: "",
  },
  {
    cod: "4",
    name: "Fusion",
    price: 6.99,
    unit: "un",
    size: "1L",
    marca: "",
    category: "Bebidas",
    description: "",
    image: "",
  },
  {
    cod: "5",
    name: "Nescaú",
    price: 13.0,
    unit: "un",
    size: "400g",
    marca: "",
    category: "Bebidas",
    description: "",
    image: "",
  },
  {
    cod: "6",
    name: "Água Sanitária",
    price: 2,
    unit: "un",
    size: "1L",
    marca: "",
    category: "Limpeza",
    description: "",
    image: "",
  },
  {
    cod: "7",
    name: "Cream Cracker",
    price: 6.0,
    unit: "un",
    size: "400g",
    marca: "",
    category: "Massas",
    description: "",
    image: "",
  },
  {
    cod: "8",
    name: "Bolacha Maria",
    price: 6.0,
    unit: "un",
    size: "400g",
    marca: "",
    category: "Massas",
    description: "",
    image: "",
  },
  {
    cod: "9",
    name: "Sardinha",
    price: 5.5,
    unit: "un",
    size: "125g",
    marca: "",
    category: "Proteinas",
    description: "",
    image: "",
  },
  {
    cod: "10",
    name: "Atum",
    price: 8.5,
    unit: "un",
    size: "125g",
    marca: "",
    category: "Proteinas",
    description: "",
    image: "",
  },
  {
    cod: "11",
    name: "Tomate",
    price: 7,
    unit: "kg",
    size: "",
    marca: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "12",
    name: "Cebola",
    price: 5.0,
    unit: "kg",
    size: "",
    marca: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "13",
    name: "Manga",
    price: 10.0,
    unit: "kg",
    size: "",
    marca: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "14",
    name: "Maçã",
    price: 11.0,
    unit: "kg",
    size: "",
    marca: "fuji",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "15",
    name: "Pão de Forma Integral",
    price: 15.0,
    unit: "un",
    size: "500g",
    marca: "Plus Vita",
    category: "Massas",
    description: "",
    image: "",
  },
  {
    cod: "16",
    name: "Ovos",
    price: 10.0,
    unit: "dz",
    size: "",
    marca: "",
    category: "Proteinas",
    description: "",
    image: "",
  },
  {
    cod: "17",
    name: "Requeijão Light",
    price: 7.0,
    unit: "un",
    size: "200g",
    marca: "",
    category: "Frios",
    description: "",
    image: "",
  },
];

export default products;
